### ISSUE TITLE
最新版运行会出错

### ISSUE THREAD

**Issue by river1** [fffonion/Xunlei-Fastdick#106]
Warning: pycrypto not found, use pure-python implemention
Traceback (most recent call last):
  File "F:\River\Downloads\swjsq (1).py", line 800, in <module>
    ins.run(uid, pwd_md5, save = False)
  File "F:\River\Downloads\swjsq (1).py", line 373, in run
    print('Login xunlei succeeded')
  File "F:\River\Downloads\swjsq (1).py", line 180, in print
    logfd.write(line)
TypeError: a bytes-like object is required, not 'str'

[这个版本](https://github.com/fffonion/Xunlei-Fastdick/tree/486352c00cab802332e7d2b058c46cbb5b2bfabe)还是好的

**Comment by fffonion** [comment]
这样应该没问题啦
