### ISSUE TITLE
异常：UnicodeEncodeError  |  ins.run(uid, hashlib.md5(pwd).hexdigest())

### ISSUE THREAD

**Issue by mmmrt** [fffonion/Xunlei-Fastdick#118]
<运行环境>
Python3.6
Openwrt 12（MiWifi改固件）

<警告>
Warning: pycrypto not found, use pure-python implemention

<异常>
```
 b'Error: login xunlei failed, \xe6\x82\xa8\xe7\x9a\x84\xe5\xb8\x90\xe5\x8f\xb7\xe5\xad\x98\xe5\x9c\xa8\xe5\xbc\x82\xe5\xb8\xb8,\xe8\xaf\xb7\xe7\x99\xbb\xe5\xbd\x95\xe5\xae\x89\xe5\x85\xa8\xe4\xb8\xad\xe5\xbf\x83\xe7\xa1\xae\xe8\xae\xa4\xef\xbc\x81'
Traceback (most recent call last):
  File "swjsq/swjsq.py", line 800, in <module>
    ins.run(uid, hashlib.md5(pwd).hexdigest())
  File "swjsq/swjsq.py", line 374, in run
    print(dt)
  File "swjsq/swjsq.py", line 190, in print
    _real_print(line, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 111-118: ordinal not in range(128)
```

<运营商>
广州电信

**Comment by fffonion** [comment]
合并 #97
