### ISSUE TITLE
urllib2.urlerror

### ISSUE THREAD

**Issue by reizhi** [fffonion/Xunlei-Fastdick#125]
Traceback (most recent call last):
  File "C:\Users\reizhi\Documents\fd\swjsq.py", line 780, in <module>
    ins = fast_d1ck()
  File "C:\Users\reizhi\Documents\fd\swjsq.py", line 179, in __init__
    self.api_up_url = api_url(up = True)
  File "C:\Users\reizhi\Documents\fd\swjsq.py", line 109, in api_url
    portal = json.loads(http_req("http://api%s.%sportal.swjsq.vip.xunlei.com:%d/v2/queryportal" % cmb))
  File "C:\Users\reizhi\Documents\fd\swjsq.py", line 169, in http_req
    resp = urllib2.urlopen(req, data = body, timeout = 60)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10060] >

启动后直接报错

**Comment by derekhe** [comment]
+1

**Comment by derekhe** [comment]
@reizhi 我看了下是http://api.upportal.swjsq.vip.xunlei.com:80/v2/queryportal
这个接口异常，上行提速不信。迅雷快屌自己也不行。
论坛里面已经有人提到了：http://bbs.xunlei.com/forum.php?mod=viewthread&tid=3178033&extra=page%3D1

迅雷产品垃圾到不行，到期后绝不使用

**Comment by fanck0605** [comment]
![default](https://user-images.githubusercontent.com/28819315/35479248-a69095fe-042d-11e8-8369-531ffac5dff6.png)
我也有报错

**Comment by derekhe** [comment]
现在已经恢复，可以关贴了
