### ISSUE TITLE
无法登录，UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b

### ISSUE THREAD

**Issue by MEZboy** [fffonion/Xunlei-Fastdick#137]
**具体报错如下，已试过改密码、更新最新swjsq.py。**
Traceback (most recent call last):
  File "swjsq.py", line 816, in <module>
    ins.run(uid, pwd)
  File "swjsq.py", line 344, in run
    dt = _lm()
  File "swjsq.py", line 338, in <lambda>
    login_methods = [lambda : self.login_xunlei(uname, pwd)]
  File "swjsq.py", line 245, in login_xunlei
    ct = http_req('https://mobile-login.xunlei.com:443/login', body=json.dumps(_payload), headers=header_xl, encoding='utf-8')
  File "swjsq.py", line 175, in http_req
    ret = resp.read().decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by fffonion** [comment]
并入#136 讨论
