### ISSUE TITLE
API 404错误

### ISSUE THREAD

**Issue by SuzukiHonoka** [fffonion/Xunlei-Fastdick#155]
之前都能正常运行的，
今天突然无法加速了，
提示API 404错误，
以下是报错内容。
`root@starx:/home/starx/Xunlei-Fastdick# python swjsq.py
Traceback (most recent call last):
  File "swjsq.py", line 828, in <module>
    ins = fast_d1ck()
  File "swjsq.py", line 197, in __init__
    self.api_up_url = api_url(up = True)
  File "swjsq.py", line 119, in api_url
    portal = json.loads(http_req("http://api%s.%sportal.swjsq.vip.xunlei.com:%d/v2/queryportal" % cmb))
  File "swjsq.py", line 179, in http_req
    resp = urllib2.urlopen(req, data = body, timeout = 60)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found`

**Comment by SuzukiHonoka** [comment]
已知可能是内部DNS劫持问题。
