### ISSUE TITLE
最近运行脚本报错

### ISSUE THREAD

**Issue by lxsjgzs** [fffonion/Xunlei-Fastdick#156]
前几天还可以的最近几天运行的时候会报错，是否是迅雷那边更新了加速方式？

以下为错误日志

[1] 1873
root@ubuntu:~/Xunlei-Fastdick# Traceback (most recent call last):
  File "swjsq.py", line 828, in <module>
    ins = fast_d1ck()
  File "swjsq.py", line 197, in __init__
    self.api_up_url = api_url(up = True)
  File "swjsq.py", line 119, in api_url
    portal = json.loads(http_req("http://api%s.%sportal.swjsq.vip.xunlei.com:%d/v2/queryportal" % cmb))
  File "swjsq.py", line 179, in http_req
    resp = urllib2.urlopen(req, data = body, timeout = 60)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error

**Comment by frostnotfall** [comment]
俺也一样
之前运行sh脚本的方式失效了，然后直接跑python，现在Python脚本也不行了，域名还在，貌似请求方式变了

**Comment by long2ice** [comment]
是的，运行不了了

**Comment by lxsjgzs** [comment]
> 是的，运行不了了



> 俺也一样
> 之前运行sh脚本的方式失效了，然后直接跑python，现在Python脚本也不行了，域名还在，貌似请求方式变了

今天又试了试，发现貌似可以了，你那边看看呢？

**Comment by frostnotfall** [comment]
> > 是的，运行不了了
> 
> > 俺也一样
> > 之前运行sh脚本的方式失效了，然后直接跑python，现在Python脚本也不行了，域名还在，貌似请求方式变了
> 
> 今天又试了试，发现貌似可以了，你那边看看呢？

果然，今天试了下没问题了，关闭issue吧
