### ISSUE TITLE
[bug] 提速失效，可能是迅雷的接口换了，ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by GrayXu** [fffonion/Xunlei-Fastdick#177]
```
$ python swjsq.py
Traceback (most recent call last):
  File "swjsq.py", line 877, in <module>
    session = json.loads(f.readline())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by GrayXu** [comment]
but it works today... weird..
