### ISSUE TITLE
Openwrt运行python版本报错

### ISSUE THREAD

**Issue by jemyzhang** [fffonion/Xunlei-FastDick#22]
很可惜，无法升级：业务处理错误：用户线路暂不具备提速能力

```
Traceback (most recent call last):
  File "swjsq.py", line 411, in <module>
    fast_d1ck(uid, hashlib.md5(pwd).hexdigest(), TYPE_NORMAL_ACCOUNT)
  File "swjsq.py", line 209, in fast_d1ck
    print('Error: can not upgrade, so sad TAT %s' % _['message'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 35-53: ordinal not in range(128)
```

change 
```
print('Error: can not upgrade, so sad TAT %s' % _['message']) 
```
->
```
print('Error: can not upgrade, so sad TAT %s' % _['message'].encode('utf-8'))
```

**Comment by fffonion** [comment]
噫，用官方客户端能升级不

**Comment by cor961** [comment]
是电信或者迅雷那边的问题吧？前两天我也是这个错误，重启光猫、路由换IP和使用迅雷快鸟都没用，当天晚上才恢复。
