### ISSUE TITLE
今天失效了？

### ISSUE THREAD

**Issue by laincat** [fffonion/Xunlei-Fastdick#36]
之前都用得好好的。。。
```
D:\Program Files (x86)\Xunlei-FastDick
λ "D:\Program Files (x86)\pypy\pypy.exe" swjsq.py
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
Traceback (most recent call last):
  File "swjsq.py", line 455, in <module>
    fast_d1ck(uid, hashlib.md5(pwd).hexdigest(), TYPE_NORMAL_ACCOUNT)
  File "swjsq.py", line 236, in fast_d1ck
    _ = api('bandwidth', dt['userID'])
  File "swjsq.py", line 204, in api
    return json.loads(http_req(url, headers = header_api))
  File "swjsq.py", line 149, in http_req
    resp = urllib2.urlopen(req, data = body)
  File "D:\Program Files (x86)\pypy\lib-python\2.7\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Program Files (x86)\pypy\lib-python\2.7\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "D:\Program Files (x86)\pypy\lib-python\2.7\urllib2.py", line 449, in _open
    '_open', req)
  File "D:\Program Files (x86)\pypy\lib-python\2.7\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "D:\Program Files (x86)\pypy\lib-python\2.7\urllib2.py", line 1235, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Program Files (x86)\pypy\lib-python\2.7\urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
```

**Comment by fffonion** [comment]
用app或者pc客户端行不行？

**Comment by laincat** [comment]
看来是我的网络环境出问题了，重启猫和路由好了。。。。抱歉，没好好检查。。。
