### ISSUE TITLE
Win命令行CTRL+C退出

### ISSUE THREAD

**Issue by CNMan** [fffonion/Xunlei-Fastdick#6]
```
Traceback (most recent call last):
  File "E:\dev\python-2.7.10.amd64\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "swjsq.py", line 219, in <lambda>
    atexit.register(lambda: api('recover', dt['userID'], dt['sessionID']))
  File "swjsq.py", line 179, in api
    return json.loads(http_req(url, headers = header_api))
  File "swjsq.py", line 129, in http_req
    resp = urllib2.urlopen(req, data = body)
  File "E:\dev\python-2.7.10.amd64\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "E:\dev\python-2.7.10.amd64\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "E:\dev\python-2.7.10.amd64\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "E:\dev\python-2.7.10.amd64\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "E:\dev\python-2.7.10.amd64\lib\urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "E:\dev\python-2.7.10.amd64\lib\urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "E:\dev\python-2.7.10.amd64\lib\httplib.py", line 1132, in getresponse
    response.begin()
  File "E:\dev\python-2.7.10.amd64\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "E:\dev\python-2.7.10.amd64\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "E:\dev\python-2.7.10.amd64\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "E:\dev\python-2.7.10.amd64\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "swjsq.py", line 219, in <lambda>
    atexit.register(lambda: api('recover', dt['userID'], dt['sessionID']))
  File "swjsq.py", line 179, in api
    return json.loads(http_req(url, headers = header_api))
  File "swjsq.py", line 129, in http_req
    resp = urllib2.urlopen(req, data = body)
  File "E:\dev\python-2.7.10.amd64\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "E:\dev\python-2.7.10.amd64\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "E:\dev\python-2.7.10.amd64\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "E:\dev\python-2.7.10.amd64\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "E:\dev\python-2.7.10.amd64\lib\urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "E:\dev\python-2.7.10.amd64\lib\urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "E:\dev\python-2.7.10.amd64\lib\httplib.py", line 1132, in getresponse
    response.begin()
  File "E:\dev\python-2.7.10.amd64\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "E:\dev\python-2.7.10.amd64\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "E:\dev\python-2.7.10.amd64\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt

e:\Program Files\Thunder Network>
```

**Comment by fffonion** [comment]
ctrl+c退出的时候会恢复原速(发一个recover)，不要急www
急的话直接叉掉就行了

**Comment by CNMan** [comment]
```
Microsoft Windows [版本 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

E:\Program Files\Thunder Network>python swjsq.py
Login xunlei succeeded
To Upgrade: XX电信 Down 8M -> 30M, Up 1M -> 10M
Initializing upgrade
Error: already speed up
```

最近运行都提示already speed up

**Comment by fffonion** [comment]
这你要问迅雷wwwww

**Comment by CNMan** [comment]
@fffonion 我猜测是脚本 非正常 退出，没发recover导致的

**Comment by fffonion** [comment]
@CNMan 有可能，这种情况其实重新拨一下宽带也可以（只要IP变了就行）

**Comment by CNMan** [comment]
@fffonion 能不能启动的时候先发一个recover？

**Comment by fffonion** [comment]
@CNMan 你自己改一下吧，逻辑有点诡异www

**Comment by CNMan** [comment]
@fffonion 不会编程啊，尴尬...

**Comment by fffonion** [comment]
@CNMan  试试这个分支https://github.com/fffonion/Xunlei-FastDick/tree/issue-6

**Comment by CNMan** [comment]
@fffonion 多谢:)
发现个新的问题，有时候启动不提速，反而降速了
运行几次才能成功提速

```

E:\Program Files\Thunder Network>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
Error: can not upgrade, so sad TAT

E:\Program Files\Thunder Network>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
Error: can not upgrade, so sad TAT

E:\Program Files\Thunder Network>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
Error: can not upgrade, so sad TAT

E:\Program Files\Thunder Network>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
To Upgrade: XX电信 Down 8M -> 30M, Up 1M -> 10M
Initializing upgrade
Upgrade done: Down 0M, Up 0M

E:\Program Files\Thunder Network>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
To Upgrade: XX电信 Down 8M -> 30M, Up 1M -> 10M
Initializing upgrade
Error:

E:\Program Files\Thunder Network>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
To Upgrade: XX电信 Down 8M -> 30M, Up 1M -> 10M
Initializing upgrade
Upgrade done: Down 30M, Up 0M
```

**Comment by CNMan** [comment]
Error: already speed up 的问题还是存在
