### ISSUE TITLE
queryportal获得的ip和端口无法连接

### ISSUE THREAD

**Issue by wsxx0321** [fffonion/Xunlei-Fastdick#75]
环境：win7下的Python35
坐标：帝都联通
账户：炒鸡会员
人员：小白一枚
请求：大神助我
ps:win下客户端运行可正常加速
使用cmd运行报错：

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\X_xin>cd C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32

C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
Traceback (most recent call last):
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\urllib\requ
est.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\http\client
.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\http\client
.py", line 1151, in _send_request
    self.endheaders(body)
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\http\client
.py", line 1102, in endheaders
    self._send_output(message_body)
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\http\client
.py", line 934, in _send_output
    self.send(msg)
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\http\client
.py", line 877, in send
    self.connect()
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\http\client
.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\socket.py",
 line 711, in create_connection
    raise err
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\socket.py",
 line 702, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没
有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "swjsq.py", line 628, in <module>
    fast_d1ck(uid, pwd_md5, TYPE_NUM_ACCOUNT, save = False)
  File "swjsq.py", line 306, in fast_d1ck
    _ = api('bandwidth', dt['userID'])
  File "swjsq.py", line 276, in api
    return json.loads(http_req(url, headers = header_api))
  File "swjsq.py", line 171, in http_req
    resp = urllib2.urlopen(req, data = body)
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\urllib\requ
est.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\urllib\requ
est.py", line 466, in open
    response = self._open(req, data)
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\urllib\requ
est.py", line 484, in _open
    '_open', req)
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\urllib\requ
est.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\urllib\requ
est.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\X_xin\AppData\Local\Programs\Python\Python35-32\lib\urllib\requ
est.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没
有正确答复或连接的主机没有反应，连接尝试失败。>

**Comment by fffonion** [comment]
浏览器打开 http://api.portal.swjsq.vip.xunlei.com:81/v2/queryportal 显示啥

**Comment by wsxx0321** [comment]
内牛满面啊感谢大神理睬{"errno":0,"interface_ip":"122.143.5.71","interface_port":"80","message":"","province":"bei_jing","province_name":"北京","sp":"cnc","sp_name":"联通"}

**Comment by fffonion** [comment]
不造为啥这个端口不开 😿 
？？？？？

**Comment by wsxx0321** [comment]
或许这就是帝都的命数...感谢大神！

**Comment by fffonion** [comment]
试试新的？

**Comment by MrEsquire** [comment]
更新的版本后，问题解决了，谢谢！

**Comment by wsxx0321** [comment]
完美可用，感谢大神..效率太高了！
