### ISSUE TITLE
每次都会卡在“login xunlei  succeeded”这个环节 

### ISSUE THREAD

**Issue by MrEsquire** [fffonion/Xunlei-Fastdick#76]
运营商:电信
地    点:湖北
账号类型:超级会员
系    统:win10
python:2.7
昨天可以成功加速 ，可是今天运行swjsq会一直卡在“login xunlei  succeeded”这个位置 
路由器则显示:
login xunlei
session is CC43FD220EBC304CDACC2ED2860DB56A
uid is 321842246
upgrade
会一直卡着不动 
电脑迅雷快鸟客户端运行正常 ，可正常提速 
log文:
Login xunlei succeeded
Traceback (most recent call last):
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 877, in send
    self.connect()
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\socket.py", line 711, in create_connection
    raise err
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\drsou\Desktop\Xunlei-Fastdick-master\swjsq.py", line 628, in <module>
    fast_d1ck(uid, pwd_md5, TYPE_NUM_ACCOUNT, save = False)
  File "C:\Users\drsou\Desktop\Xunlei-Fastdick-master\swjsq.py", line 306, in fast_d1ck
    _ = api('bandwidth', dt['userID'])
  File "C:\Users\drsou\Desktop\Xunlei-Fastdick-master\swjsq.py", line 276, in api
    return json.loads(http_req(url, headers = header_api))
  File "C:\Users\drsou\Desktop\Xunlei-Fastdick-master\swjsq.py", line 171, in http_req
    resp = urllib2.urlopen(req, data = body)
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\drsou\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

**Comment by fffonion** [comment]
和#75 是同一个问题
试试刚才更新的版本吧
