### ISSUE TITLE
运行脚本错误

### ISSUE THREAD

**Issue by 498110811** [fffonion/Xunlei-Fastdick#89]
怎么PC和路由器都是一样错误

**Comment by fffonion** [comment]
贴下什么错误啊😂

**Comment by 498110811** [comment]
root@XiaoQiang:~# cd /data/usr/bin/swjsq
root@XiaoQiang:/data/usr/bin/swjsq# python ./swjsq.py
Warning: pycrypto not found, use pure-python implemention
Traceback (most recent call last):
  File "./swjsq.py", line 643, in <module>
    fast_d1ck(uid, hashlib.md5(pwd).hexdigest())
  File "./swjsq.py", line 297, in fast_d1ck
    dt, _payload = login_xunlei(uname, pwd)
  File "./swjsq.py", line 224, in login_xunlei
    ct = http_req('https://login.mobile.reg2t.sandai.net:443/', body = _payload, headers = header_xl, encoding = 'gbk')
  File "./swjsq.py", line 179, in http_req
    ret = resp.read().decode(encoding)
UnicodeDecodeError: 'gbk' codec can't decode bytes in position 678-679: illegal multibyte sequence
root@XiaoQiang:/data/usr/bin/swjsq#

**Comment by 498110811** [comment]
这个错误提示

**Comment by fffonion** [comment]
能把179行改成`ret = resp.read()`再运行下吗

**Comment by 498110811** [comment]
Warning: pycrypto not found, use pure-python implemention
Traceback (most recent call last):
  File "./swjsq.py", line 643, in <module>
    fast_d1ck(uid, hashlib.md5(pwd).hexdigest())
  File "./swjsq.py", line 297, in fast_d1ck
    dt, _payload = login_xunlei(uname, pwd)
  File "./swjsq.py", line 225, in login_xunlei
    return json.loads(ct), _payload
  File "/userdisk/python/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/userdisk/python/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/userdisk/python/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xcd in position 0: invalid continuation byte
这是修改后运行的 结果

**Comment by fffonion** [comment]
我感觉是路由器没有locale的关系错误打不出来，pc上应该可以，试下pc上是什么错误？
